source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SMSegmentView_Example', :exclusive => true do
  pod "SMSegmentView", :path => "../"
end

target 'SMSegmentView_Tests', :exclusive => true do
  pod "SMSegmentView", :path => "../"

  
end
